### ISSUE TITLE
Add a HEALTHCHECK to Docker image

### ISSUE THREAD

**Issue by stuartc** [OpenFn/kit#842]
### Details

All docker deployments should have heath checks built in, right now we have to specify the health check via the compose file.

Eg:

```yaml
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2222"]
      interval: 30s
      timeout: 5s
      retries: 5
```

### User acceptance criteria

Running the image without specifying the heath check should work automagically.
