### ISSUE TITLE
CLI deploy: enable better name conversation

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#901]
v2 is more strict about workflow names than v1.

When migrating v1 projects with CLI deploy, we should be able to run a safe slugify function to strip out disallowed characters.

I expect this to be almost a one liner.

I guess the only question is if this creates any kind of sync problem. Do we only convert on first deploy or do we do it always?

**Comment by josephjclark** [comment]
These real workflow names and step names cause problems:
```
Workflow-[BNS-1B]-1.Get-FormsList-(Historical-sync):
    name: Workflow [BNS-1B] 1.Get FormsList (Historical sync)
    jobs:
      [BNS-1B]-1.Get-FormsList-(Historical-sync):
        name: [BNS-1B] 1.Get FormsList (Historical sync)
        adaptor: '@openfn/language-googlesheets@v2.3.0'
        body:
```
